### ISSUE TITLE
Error when setting up webhooks

### ISSUE THREAD

**Issue by DanielTheGeek** [PaystackOSS/paystack-cli#2]
I'm having an issue setting up webhooks using the Paystack CLI. It returns an error anytime I run `webhook ping --event transfer.success --domain test`

Here's the response:
The response:
`Sending sample transfer.success event payload to null
(node:7272) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
at C:\Users\Oreoluwa\AppData\Roaming\npm\node_modules\@paystack-oss\dev-cli\lib\Paystack.js:135:38
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:7272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by edwardsmoses** [comment]
First, you've to tunnel your test events to your local server running on a port. 
Assuming your port Is **8080**, you run
`webhook --domain test listen localhost:8000`.
